package com.boutique.domain.promociones.impl;

public enum PromocionTypeEnum {
	DESCUENTO_GENERAL,
	PRECIO_GENERAL,
	DESCUENTO_POR_TIPO_DE_PRODUCTO, 
	DESCUENTO_POR_PRODUCTOS_SELECCIONADOS,
	DESCUENTO_PROXIMA_COMPRA, 
	REBAJA_PROXIMA_COMPRA, 
	PUNTOS_AL_CLIENTE,
}
